title: ss
description: ss
template:
  repo: ss-template
  name: ss
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: New step
    description: The second step in your course
    event: issues.assigned
    actions:
      - type: createIssue
        title: A new issue
        body: new-issue.md
